lib/application.js, lib/mixins/promise.js, package.json, test/mixins/event.test.js, test/mixins/promise.test.js, test/providers/primus.test.js
This pull request fixes the Uberproto hack from #100 and corrects the promise mixin to only work with functions.
=> Use Uberproto extended instance when creating services

lib/application.js, lib/mixins/index.js, test/application.test.js
This pull request fixes a bug that cause weird issues. The reason was that an applications `mixins` array was shared through *every* Feathers application.
=> Make sure that mixins are specific to each new app

lib/application.js, lib/mixins/event.js, lib/providers/socket/commons.js, lib/providers/socket/primus.js, lib/providers/socket/socketio.js, test/application.test.js, test/providers/primus.test.js, test/providers/rest.test.js, test/providers/socketio.test.js
This is Dynamic Services on top of the recent 1.0.2 patch.  I've also made it no longer a requirement to pass a callback (#96).  If the request fails, it logs a message to the console for a developer to track down.
As for consolidating the code a bit more.  This is basically creating a second path in the code to setup a service.  The first way is through the setup methods, and now this for sure works after the server has started.  I'm not sure if it would be possible to just use this new way BEFORE the server starts.  I would have to check to see if there is anything that the setup methods put in place that the services require as prerequisites.
**Update:** We for sure have to wait until the providers are set in place, which isn't really guaranteed until after the server starts (since …
=> Dynamic services 2

lib/application.js, test/application.test.js, test/providers/primus.test.js, test/providers/socketio.test.js
Setup() wasn't being run on dynamic services.  I've included a fix and updated one of the tests to make sure setup runs.
Oh, I also moved `stripSlashes(location)` to the top of app.service() and replaced all duplicate instances of it with `location`.
=> Make sure .setup() runs on dynamic services.

lib/application.js, lib/mixins/event.js, lib/providers/socket/commons.js, lib/providers/socket/primus.js, lib/providers/socket/socketio.js, test/providers/primus.test.js, test/providers/rest.test.js, test/providers/socketio.test.js
After fixing setup() for dynamic services in the last PR (#110), the events mixin's setup() function was adding duplicate events.  This PR wraps `applyEvents` with an `if (!this._serviceEvents) { ... }` check to assure it isn't adding events twice.
=> Fix duplicate events in dynamic services.

.travis.yml, package.json, test/providers/primus.test.js, test/providers/socketio.test.js
This pull request adds tests for the latest [feathers-commons](https://github.com/feathersjs/feathers-commons) functionality which allows Socket message validation and to omit parameters and calls back with an error when wrong arguments are submitted. Closes #96 and closes #113. /cc @marshallswain
=> Tests for socket message validation and errors.

lib/mixins/index.js, lib/mixins/normalizer.js, lib/mixins/promise.js, test/application.test.js, test/mixins/normalizer.test.js
#123 added method normalization to Socket calls. As discussed, this pull request instead adds a mixin that always normalizes all method calls. It will always be added as the last mixin (and therefore the first to run) which also makes sure that plugins like [feathers-hooks](https://github.com/feathersjs/feathers-hooks) won't have to worry about normalizing the parameters.
=> Service method call normalization

lib/providers/socket/primus.js, lib/providers/socket/socketio.js, test/providers/primus.test.js, test/providers/socketio.test.js
This pull request makes sure that the SocketIO and Primus configuration callbacks are called *before* the services `.setup` is called so that you can access `app.io` and `app.primus`. Closes #131
=> Run Socket configurations before service setup (#131)

lib/mixins/event.js, package.json, test/distributed.test.js, test/mixins/event.test.js
This pull request allows to register services that are already event emitters. Works great with [feathers-client](https://github.com/feathersjs/feathers-client/) which makes it possible to use remote services from other servers.
Closes #118
=> Allow to register remote services

lib/providers/rest/index.js, test/providers/rest.test.js
The way the routes are created by the REST provider prevent 404 errors being properly thrown.
To reproduce, just run the feathers todo-list demo and browse to an URL like `/todos/foo/bar`, it won’t return a 404 as it should but a 200 without any content (because of the `app.use(uri, handler);` statement catching any URLs starting with `/todos`)
=> Fix 404 not being properly thrown by REST provider

lib/application.js, lib/mixins/event.js, test/application.test.js, test/mixins/event.test.js
This pull request makes sure that event punching happens after methods normalization. The issue before was that you couldn't call methods on the server without a callback (which isn't necessary).
Closes #150
=> Make sure event hookups happens after method normalization

test/providers/primus.test.js, test/providers/socketio.test.js
This pull requests makes sure that `feathers-commons` set the event filter context to the service (see https://github.com/feathersjs/feathers-commons/issues/5). No new release necessary since it should be pulled in automatically on new installations.
=> Adding tests to make sure that dispatcher context is set properly.

package.json, src/application.js, src/feathers.js, src/mixins/event.js, test/mixins/event.test.js
Because ES6 is awesome we don't really need Lodash anymore (`feathers-commons` doesn't use it already). It also makes the client build a lot easier (and smaller).
=> Remove Lodash

client.js, package.json, src/application.js, src/client/express.js, src/client/index.js, src/feathers.js, test/application.test.js, test/client.test.js, test/mixins/event.test.js, test/mixins/normalizer.test.js, test/mixins/promise.test.js
This pull request adds a client side shim for Express, allowing to use Feathers in non-Node environments like the Browser and React Native to build fully universal applications with Feathers best practises like services and hooks. The Browserified build is around 8k minified and gzipped.
Also adds a `.defaultService` functionality. This will be needed when initializing non-existing services on the client which should then just connect to their configured endpoint as it is already done in [feathers-client](https://github.com/feathersjs/feathers-client).
Closes #191
=> Make Feathers universal

package.json
This adds a Node Security Project scan to the end of the tests.
=> Appending `nsp check` to test script.

src/client/index.js
Some loaders (like Webpack) can not require JSON by default so it is best to take out requiring the package to get the version. This will also make built versions a little smaller. The drawback is that we will have to update those versions manually (maybe remove them entirely in 3.0).
=> Remove JSON loading from the client version

index.d.ts
As specified in #520, 
> I've seems to have found an issue. Shouldn't the pagination interface be like
> ```
> interface Pagination <T> {
>    total: Number,
>    limit: Number,
>    skip: Number,
>    data: T[] // As in, with an array instead of a single object?
>}
```
=> Fix pagination type definition.

index.d.ts
optional
As per the [current type definition of Service ](https://github.com/feathersjs/feathers/blob/master/index.d.ts#L23), all the service methods are required methods. 
But according to documentation, service methods are optional . 
See 
So, service definition should be something like below
```typescript
interface Service<T> extends events.EventEmitter {
find?(params?: Params, callback?: any): Promise<T[] | Pagination<T>>;
get?(id: number | string, params?: Params, callback?: any): Promise<T>;
create?(data: T | T[], params?: Params, callback?: any): Promise<T | T[]>;
update?(id: NullableId, data: T, params?: Params, callback?: any): Promise<T>;
patch?(id: NullableId, data: any, params?: Params, callback?: any): Promise<T>;
remove?(id: NullableId, params?: Params, callback?: any): …
```
=> Fix typescript defnition of Service. All the service methods should be

readme.md
The commit https://github.com/feathersjs/feathers/commit/60b1f330624a76846e6d6efa0ea6db295c260731 pointed some links in the readme to the legacy security docs, because the security page was down. 
The PR https://github.com/feathersjs/feathers-docs/pull/646 in the feathers-doc repo re-adds the security page.
This negates the point of the first commit, so this PR is to revert https://github.com/feathersjs/feathers/commit/60b1f330624a76846e6d6efa0ea6db295c260731, since it it is no longer necessary.
No
No, the PR in the feathers-docs repo has already been merged here https://github.com/feathersjs/feathers-docs/pull/646
=> Revert update to security links

.babelrc, package.json, src/index.js, test/application.test.js, yarn.lock
This inlines the current version as `feathers.version` using https://github.com/gnandretta/babel-plugin-version-inline
=> Use inline version Babel plugin

src/hooks.js, test/application.test.js, test/hooks/hooks.test.js
This will be used by the updated providers (primarily to retrieve `hook.dispatch` which will contain the "safe" data to send to a client). Allows to do something like:
```js
app.service('dummy').find({
__returnHook: true
}).then(hook => {
// hook is the actual hook object instead of just the result
});
```
=> Allow flag to return the hook object

lib/hooks.js, test/hooks/after.test.js, test/hooks/error.test.js, test/hooks/hooks.test.js
This allows error hooks to normally resolve by setting `hook.result` instead of always throwing the error.
Closes https://github.com/feathersjs/feathers-hooks/issues/151
=> Allows error hooks to swallow error by setting the result

index.d.ts
A little problem with the typescript definition without configure() method in Application interface
=> Add a missing configure() method in typescript definition

LICENSE, client.js, lib/application.js, lib/events.js, test/application.test.js
This basically re-registers all services from a sub-app on the mountpath which should take care of most cases (and be faster than the old Express way).
=> Add support for Feathers v3 sub-apps

lib/hooks.js, test/hooks/hooks.test.js
In some cases - specifically for the service providers - we want to allow to return the hook object instead of only the result from a method call. This used to be possible by setting `params.__returnHook` but it is too easy to blow `params` away in a hook chain.
This new way returns the hook object if the last parameter in a service call is `true`.
=> Better logic for returning the hook object from method call

lib/application.js, test/application.test.js
For #718 and #728 as well as avoiding the cryptic error of `stripSlashes` trying to run `name.replace` on a non-string.
=> Throw an error for invalid service paths

lib/hooks.js, test/hooks/hooks.test.js
When returning the hook object previously it was not possible to swallow the error. This should fix it.
Closes https://github.com/feathersjs/feathers/issues/767
=> Properly resolve the promise in error hooks if returnHook is set.

lib/hooks.js, test/hooks/hooks.test.js
Feathers argument validation ran outside the normal hook chain which causes a bug when the hook object is expected to be returned, e.g. in the REST and websocket API transports and it skipped error hooks. The solution was to make it the very first hook in the chain so it will be treated like any other error.
Closes https://github.com/feathersjs/express/issues/19
=> Turn argument validation into the first hook

lib/hooks.js, test/hooks/error.test.js
This is a backwards compatible fix for #841
=> Make sure error hooks always have the original context information

lib/hooks.js, package-lock.json, test/hooks/error.test.js
I do not know if this modification will break the tests of other packages of the ecosystem (I do not think) but it seems normal to me to be able to return null value without it being an error.
In my case I need to return null when I get a `softDelete`d item instead of throw an error, the following code works with this PR:
```js
// For return `null` value after a get on a soft deleted event I need to avoid error
error( context ) {
if ( context.error instanceof errors.NotFound && context.error.message === 'Item not found.' ) {
context.result = null;
return context;
}
log.error(
`Error in '${context.path}' service method '${context.method}'\n${context.error.stack}\n`,
inspect( _.omit( context.error, [ 'hook.app', 'hook.service' ] ), { colors: true } )
);
}
```
This can also be useful in a …
=> Allow methods to return a null result

packages/commons/lib/utils.js
A minimal matching is very faster than a wildcard matching in RegExp object, specially for long string case.
A test case gist at: https://gist.github.com/xixilive/99f4dc4dc175ca0386cb6e34d5f24ac1
this test case output on my machine:
Strip with wildcard matching
Time of strip1:: `540.535ms`
Strip with minimal matching
Time of strip2:: `272.998ms`
Closes https://github.com/feathersjs/feathers/issues/976
=> use minimal RegExp matching for more performance

.travis.yml, package.json, packages/generator-feathers-plugin/package.json, packages/generator-feathers-plugin/test/test-creation.js, packages/generator-feathers/package.json
They are not running by default with `npm test` because it takes a while and you need several databases installed. They should run on CI however.
=> Re-enable tests for generators in CI

packages/generator-feathers/generators/app/templates/src/hooks/log.js
When you swallow an error you expect silence... this common built in hook makes it noisy regardless. It looks almost exactly like an uncaught error and is very deceiving
This results in handled errors looking like this:
```
info: error: mailer - Method: create: getaddrinfo ENOTFOUND smtp.mailgun.org 
```
Instead of this:
```
info: error: mailer - Method: create: getaddrinfo ENOTFOUND smtp.mailgun.org smtp.mailgun.org:2525
error:  Error: getaddrinfo ENOTFOUND smtp.mailgun.org smtp.mailgun.org:2525
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
```
which I much prefer.
MOVED TO MONOREPO FROM: https://github.com/feathersjs/generator-feathers/pull/392#issuecomment-420408312
=> [generator-feathers] Support Logger swallowing

packages/feathers/lib/hooks/base.js, packages/feathers/test/hooks/hooks.test.js
This is a regression where things like `.find(null)` previously still turned `params` into an object. The new argument normalization overwrote it with any other value.
Closes #1001, closes #1011, closes https://github.com/feathersjs/authentication-client/issues/114
=> Normalize params to object even when it is falsy

packages/generator-feathers/generators/service/templates/model/mongoose-user.js
In most cases usernames and emails are case-insensitive. Current implementation prevents users from authenticating successfully when the emails do not match exactly (i.e. case sensitive).
This is just a minor change but it makes more sense to the end-user and developer as usernames in most cases do not require you to be case sensitive in the username field.
=> Allow case-insensitive for local email (username) authentication

.codeclimate.yml
Makes codeclimate a bit more relaxed. Rejects duplicates after three instances have been found instead of three.
I ran into this issue when submitting another pull request: https://github.com/feathersjs/feathers/pull/1075 but this concerns all code in general. The code in the other pull request could be reformatted but I feel it is not justified to be generized. There is strong prior agrumentation for the case: https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)
Happy Hactober!
=> feat(env): make codeclimate conform to rule of three

.travis.yml
Saucelabs tests for the client build only need to run once for a CI build not for every Node version.
=> chore: Only run Saucelabs tests once in CI

packages/authentication/lib/hooks/authenticate.js, packages/authentication/test/hooks/authenticate.test.js
Method: https://expressjs.com/en/api.html#req.method
Path: https://expressjs.com/en/api.html#req.path
But this fields are not included while creating an express like request object for passport in 
@feathersjs/authentication hook.authenticate() function.
=> Added path and method in to express request for passport

packages/adapter-commons/lib/filter-query.js, packages/adapter-commons/test/filter-query.test.js
In order to avoid issues with the database adapter updates, unknown query parameters starting with `$` should throw an error instead of just being removed. If they were just being removed, limiting queries would become more generic, causing security regressions.
=> fix: `filterQuery` throw error when query parameter is unknown

packages/adapter-commons/lib/service.js, packages/adapter-commons/test/service.test.js
So that the same thing doesn't have to be done in every sub-class.
=> fix: Add whitelist and filter support to common adapter service

packages/adapter-commons/lib/filter-query.js, packages/adapter-commons/test/filter-query.test.js, packages/adapter-commons/test/service.test.js
This is important for Sequelize which uses internal Symbols to create safe queries.
=> fix(adapter-commons): Keep Symbols when filtering a query

changelog.md, package.json
Something that came up a couple of times since individual changelogs are in the respective `packages/` directory.
=> Add a top level changelog

packages/adapter-tests/lib/methods.js, packages/adapter-tests/package-lock.json, packages/adapter-tests/test/index.test.js
Adds an explicit test that makes sure that when a different adapter `id` property is in the query it will not succeed.
=> fix: Add test to make sure different id in adapter query works

.github/lock.yml
Adds the configuration for the [lock-threads GitHub bot](https://github.com/dessant/lock-threads) that automatically locks closed issues. Comments on closed issues usually will not get a reply and should be opened as new issues instead.
=> chore: Add Lock bot configuration

packages/adapter-tests/lib/methods.js
Since using the actual package seems to be causing problems especially when different versions are being installed.
=> fix: Update adapter tests to not rely on error instance

packages/client/browser/index.html
It is causing unreliable tests on Saucelabs (probably due to the tunnel).
=> tests: Increate Mocha browser test timeout

packages/express/lib/authentication.js, packages/express/lib/index.js, packages/express/lib/rest/index.js, packages/express/package.json, packages/express/test/authentication.test.js, packages/express/test/rest/index.test.js
This pull request adds a `parseAuthentication` and `authenticate` middleware to the `@feathersjs/express` transport adapter.
=> Authentication v3 Express integration

lerna.json
Although I tried explaining the advantages of independent versioning and how Feathers is composed of individual (and optional) modules there seems to be recurring confusion about Feathers version names and numbers.
Since the new authentication system contains a lot of changes anyway, this seems like a good time to also move to fixed common versioning of all modules in this repository like Babel and others are doing already.
So Feathers Crow will be `@feathersjs/feathers` and all other `@feathersjs/*` modules version `4.x`, Dove will be `5.x` etc. There will be `4.0.0-pre` prereleases, however since `@feathersjs/transport-commons` is already at version `4.2.1` the final release of all modules will start at `4.3.0`.
=> Switch to fixed common versioning

Gruntfile.js
For some reason Saucelabs stopped working and it appears to be Safari.
=> Skip Safari in Saucelabs for now

packages/feathers/lib/events.js, packages/feathers/test/events.test.js
Allow to skip the service event by setting `context.event = null;` in a hook.
Closes #862
=> feat: Allow to skip sending service events

packages/authentication/lib/service.js, packages/commons/lib/hooks.js, packages/commons/test/hooks.test.js, packages/feathers/lib/index.js, packages/feathers/test/application.test.js, packages/feathers/test/hooks/after.test.js, packages/feathers/test/hooks/before.test.js, packages/feathers/test/hooks/error.test.js
In preparation to support Koa style hooks (see #932) this pull request
- Removes the `(context, next)` signature. This has not been documented or used since the Auk release.
- Removes `feathers.SKIP` to skip the following hooks. It turned out to cause issues because
- It is not easily possible to see if a hook makes its following hooks skip. This made hook chains very hard to debug.
- Returning SKIP also messes with Feathers internals like the event system
The use-cases for `feathers.SKIP` can now be explicitly handled by
- [Running hooks conditionally](https://feathers-plus.github.io/v1/feathers-hooks-common/#iff) through a flag
- [Calling the hook-less service methods](https://crow.docs.feathersjs.com/migrating.html#hook-less-service-methods) of the database adapters
- Setting …
=> feat: Remove (hook, next) signature and SKIP support

packages/authentication/src/core.ts, packages/authentication/src/hooks/authenticate.ts, packages/authentication/src/index.ts, packages/authentication/test/core.test.ts, packages/authentication/test/hooks/authenticate.test.ts
When running authentication strategies the `params` are being passed on but there needs to be an indicator for the `authenticate` hook to not run to avoid infinite loops (e.g. if a service called by an authentication strategy also has the `authenticate` hook). This PR adds an `AUTHENTICATE` symbol that the authentication core uses as a flag to skip the `authenticate` hook.
=> feat: Support params symbol to skip authenticate hook

packages/authentication-client/src/core.ts, packages/authentication-client/src/index.ts, packages/authentication-client/src/storage.ts, packages/authentication-client/test/index.test.ts
This allows the client to pick up the cross-domain `access_token` redirect from an oAuth authentication flow (but only if there is no local token) and sets `localStorage` as the default if it is a browser environment.
=> feat: Add authentication through oAuth redirect to authentication client

packages/express/lib/rest/index.js, packages/express/test/authentication.test.js, packages/express/test/rest/index.test.js, packages/primus/lib/index.js, packages/primus/test/index.test.js, packages/socketio/lib/index.js, packages/socketio/test/index.test.js
`params.headers` was never supposed to be available in service calls (to stay more transport independent) but the old Feathers authentication added it and it seems to be relied on a lot so this PR adds it to the transport providers themselves.
=> feat: Add params.headers to all transports when available

packages/transport-commons/src/channels/index.ts, packages/transport-commons/src/channels/mixins.ts, packages/transport-commons/test/channels/dispatch.test.ts, readme.md
`app.publish` or `service.publish` should only be called once to register a publisher. It seems the name `publish` caused some confusion and I have seen it repeatedly being called in hooks and other places where it probably shouldn't. Changing the name to `registerPublisher` to be a little more concise.
=> fix: Add registerPublisher alias for .publish

packages/authentication-local/test/strategy.test.ts, packages/authentication-oauth/test/strategy.test.ts, packages/authentication/package.json, packages/authentication/src/core.ts, packages/authentication/src/jwt.ts, packages/authentication/src/service.ts, packages/authentication/test/core.test.ts, packages/authentication/test/jwt.test.ts
Feathers authentication does not have to use JWT, it can generate any kind of accessToken. This change reflects it in the method names.
=> feat: Change and *JWT methods to *accessToken

packages/authentication-client/src/index.ts, packages/authentication-client/test/integration/fixture.ts, packages/authentication-local/src/strategy.ts, packages/authentication-local/test/fixture.js, packages/authentication-oauth/src/express.ts, packages/authentication/src/options.ts, packages/authentication/src/service.ts, packages/authentication/test/hooks/authenticate.test.ts, packages/authentication/test/jwt.test.ts, packages/authentication/test/service.test.ts
Because it is more accurate. It is a list of strategies that are allowed to create an `accessToken`.
=> fix: Rename jwtStrategies option to authStrategies

packages/authentication/src/core.ts, packages/authentication/src/hooks/authenticate.ts, packages/authentication/src/index.ts, packages/authentication/test/core.test.ts, packages/authentication/test/hooks/authenticate.test.ts
The `AUTHENTICATE` symbol was not backwards compatible but effectively doing the same thing as the previously used `params.authenticated` boolean flag so we might as well keep it that way.
=> fix: Bring back params.authenticated

packages/authentication-local/src/strategy.ts, packages/authentication-oauth/src/strategy.ts, packages/authentication-oauth/test/strategy.test.ts, packages/authentication/src/core.ts, packages/authentication/src/jwt.ts, packages/authentication/test/core.test.ts, packages/authentication/test/hooks/authenticate.test.ts, packages/authentication/test/jwt.test.ts, packages/authentication/test/service.test.ts, packages/express/test/authentication.test.js
Running through all strategies is inefficient and confusing. This PR always requires `strategy` property for authentication and will only run that strategy and return its error or success.
Closes #1323
=> fix: Always require strategy parameter in authentication

packages/authentication-local/src/strategy.ts, packages/authentication-local/test/fixture.js, packages/authentication-local/test/strategy.test.ts, packages/authentication-oauth/package-lock.json, packages/authentication/src/core.ts, packages/authentication/src/hooks/authenticate.ts, packages/authentication/src/jwt.ts, packages/authentication/test/jwt.test.ts, packages/client/package-lock.json, packages/tests/package-lock.json
For #1324 4), 5), 6) and 7) and should close #1320
=> fix: Improve authentication parameter handling

packages/authentication-oauth/src/express.ts, packages/authentication-oauth/src/index.ts, packages/authentication-oauth/src/strategy.ts, packages/authentication-oauth/src/utils.ts, packages/authentication-oauth/test/index.test.ts, packages/authentication-oauth/test/strategy.test.ts, packages/authentication-oauth/test/utils.test.ts
Pull request that should close https://github.com/feathersjs/feathers/issues/1324 specifically
- `9)` by adding an `expressSession` option to provide a custom session store
- `10)` by using both `profile.sub` and `profile.id`
- `11)` by adding `getRedirect` to the strategy (so it is also customizable on a per-strategy basis)
- `12)` by supporting the `getEntityQuery` and `getEntityData` methods that should make customization easier
@KidkArolis let me know if you see anything that's missing
=> fix: Improve oAuth option handling

packages/authentication-oauth/src/express.ts, packages/authentication-oauth/test/strategy.test.ts, packages/primus/lib/index.js, packages/primus/test/index.test.js, packages/socketio/lib/index.js, packages/socketio/test/index.test.js, packages/transport-commons/src/socket/index.ts
So you can do
```js
app.on('disconnect', connection => {
});
```
- Closes #1238
- Closes #1243
=> feat: Add global disconnect event

packages/transport-commons/src/socket/index.ts, packages/transport-commons/test/socket/index.test.ts
Adds the `authenticate` event from the old authentication so that socket clients using that format will still continue to work.
=> fix: Add fallback for legacy socket authentication

packages/authentication/src/core.ts, packages/authentication/test/core.test.ts, packages/transport-commons/test/socket/index.test.ts
=> fix: Throw NotAuthenticated on token errors

packages/authentication-client/src/core.ts, packages/authentication-oauth/package-lock.json, packages/authentication-oauth/src/express.ts, packages/authentication-oauth/src/index.ts, packages/authentication-oauth/src/strategy.ts, packages/authentication-oauth/test/express.test.ts, packages/authentication/src/jwt.ts, packages/transport-commons/test/socket/index.test.ts
This pull request makes the oAuth callback paths consistent. It uses the redirects  discussed in https://github.com/simov/grant/pull/116 to make things more straightforward and backwards compatible. Also changes the base path to `/oauth` as previously discussed with @KidkArolis (it can be made backwards compatible by setting `authentication.oauth.defaults.path` to `/auth`).
The relevant oAuth paths now are:
- `http(s)://<host>/oauth/<provider>` to initiate the oAuth flow
- `http(s)://<host>/oauth/<provider>/callback` as the callback path that should be set in the oAuth application settings
- `http(s)://<host>/oauth/<provider>/authenticate` as the internal redirect
=> fix: Make oAuth paths more consistent and improve authentication client

packages/express/test/rest.test.js, packages/feathers/lib/hooks/base.js, packages/feathers/lib/hooks/index.js, packages/feathers/test/hooks/error.test.js, packages/feathers/test/hooks/finally.test.js, packages/transport-commons/src/channels/mixins.ts
Fixes two errors:
1) `finally` hooks can possibly run twice for same method call if one of them throws. Also a `finally` hook if throws activates `error` hooks, this is in conflict with this [comment](https://github.com/feathersjs/feathers/blob/f9d8536c400caba355ccc8a2cdf171dcd9cff555/packages/feathers/lib/events.js#L77) and also `Promise.finally` and `try/catch/finally` convention. Because currently it is like this ([1](https://github.com/feathersjs/feathers/blob/f9d8536c400caba355ccc8a2cdf171dcd9cff555/packages/feathers/lib/hooks/index.js#L73), [2](https://github.com/feathersjs/feathers/blob/f9d8536c400caba355ccc8a2cdf171dcd9cff555/packages/feathers/lib/hooks/index.js#L85)):
```js
try {
run([...before])();
method();
run([...after, ...finally])();
} catch {
run([...error, ...finally])(); …
```
=> fix: Clean up hooks code

packages/express/lib/index.js, packages/express/test/rest.test.js
Using as many middleware arrays or functions as you want is valid for express, since it uses `array-flatten` on passed arguments ([1](https://github.com/expressjs/express/blob/e1b45ebd050b6f06aa38cda5aaf0c21708b0c71e/lib/router/index.js#L448), [2](https://github.com/expressjs/express/blob/e1b45ebd050b6f06aa38cda5aaf0c21708b0c71e/lib/router/route.js#L194)).
Now does not throw on valid usage for express and allows to use arrays of middleware before and after feathers service.
=> fix: @feathersjs/express: allow middleware arrays

packages/authentication-client/.npmignore, packages/authentication-local/.npmignore, packages/authentication-oauth/.npmignore, packages/authentication/.npmignore, packages/commons/.npmignore, packages/configuration/.npmignore, packages/tests/.npmignore, packages/transport-commons/.npmignore
Any drawbacks to this? 
As i understand should not affect local development as `link` command ignores `.npmignore`.
=> chore: Remove src folder from .npmignore for ts packages

packages/express/lib/rest/getHandler.js
Easier to read and faster 4 times: 500,000 vs 2,000,000 ops/sec.
Also small difference (fix): before if you `activateHooks()` some method with a nonstandard argument resulted express args getter will throw an error, now it returns valid array with `undefined` for unknown arguments. (Vanilla feathers supports nonstandard arguments, but there is no test for such case.)
Also [`makeArguments`](https://github.com/feathersjs/feathers/blob/9585ac0ee8b051c869e1b351b15da202604af244/packages/commons/src/hooks.ts#L52) and [`defaultMakeArguments`](https://github.com/feathersjs/feathers/blob/9585ac0ee8b051c869e1b351b15da202604af244/packages/commons/src/hooks.ts#L34) can be safely removed before major release, since they have been replaced with [new …
=> fix: @feathersjs/express: replace `reduce` with `map`

packages/adapter-commons/lib/service.js, packages/adapter-commons/test/service.test.js
Expose `checkMulti` as `allowsMulti`. Just like `filterQuery` it would be useful when you try to write universal hook for any adapter service and you want to support multi usage of methods but it is costly case for some reason, having such method would allow to not spend resources on something that will be rejected as invalid down the road.
=> feat: adapter-commons: add `allowsMulti(method)` to AdapterService

packages/express/errors.js, packages/express/rest.js
It is already available via `const { errorHandler } = require('@feathersjs/express');`
Closes #1441
=> fix: Remove unnecessary top level export files in @feathersjs/express

packages/express/lib/index.js, packages/express/test/index.test.js
Closes https://github.com/feathersjs/feathers/issues/1419
=> feat: @feathersjs/express allow to pass an existing Express application instance

packages/adapter-commons/src/service.ts
Reflect in id type that `update` method never supports multi-record changes.
=> fix: @feathersjs/adapter-commons: `update` id is non-nullable

packages/authentication-local/src/hooks/hash-password.ts, packages/authentication-local/src/strategy.ts, packages/authentication-local/test/hooks/hash-password.test.ts, packages/authentication-oauth/src/express.ts, packages/authentication-oauth/src/index.ts, packages/authentication-oauth/src/utils.ts, packages/authentication-oauth/test/index.test.ts, packages/authentication-oauth/test/utils.test.ts, packages/authentication/src/hooks/authenticate.ts, packages/authentication/src/service.ts, packages/authentication/test/hooks/authenticate.test.ts, packages/authentication/test/service.test.ts, packages/express/lib/authentication.js
Closes https://github.com/feathersjs/feathers/issues/1415
=> fix: Add method to reliably get default authentication service

package-lock.json, packages/authentication-oauth/src/express.ts, packages/primus/lib/index.js, packages/primus/test/index.test.js, packages/socketio/index.d.ts, packages/socketio/lib/index.js, packages/socketio/test/index.test.js, packages/transport-commons/src/socket/index.ts, packages/transport-commons/src/socket/utils.ts, packages/transport-commons/test/socket/index.test.ts, packages/transport-commons/test/socket/utils.test.ts
Instead of the Symbol workaround, we can use the WeakMap data structure for what it is supposed to which is mapping an object to another object - in our case the connection object to the socket instance.
Related to #1430
=> fix: Use WeakMap to connect socket to connection

packages/authentication/src/core.ts, packages/authentication/src/hooks/connection.ts, packages/authentication/src/hooks/event.ts, packages/authentication/src/jwt.ts, packages/authentication/src/service.ts, packages/authentication/test/jwt.test.ts, packages/socketio/test/index.test.js, packages/transport-commons/src/socket/index.ts
This pull request makes sure that authenticated real-time connections will be removed from their channels if the token expires while they are still connected or if they log out.
This should be the last thing for the v4 final release.
=> fix: Expire and remove authenticated real-time connections

packages/authentication-client/src/core.ts, packages/authentication-client/test/index.test.ts
This PR adds a `handleError` method that only removes the access token on `NotAuthenticated` errors. It can be [customized](https://crow.docs.feathersjs.com/api/authentication/client.html#customization) for custom error handling logic.
- Closes #1522
- Closes #1506
=> fix: Only remove token on NotAuthenticated error in authentication client and handle error better

packages/authentication-oauth/src/index.ts
When running on the standard port for the protocol (80 for http, 443 for https), the default oauth `redirect_uri` contains the port, which is redundant and causes the authentication request to fail in most cases.
=> Omit standard protocol ports from the default hostname

packages/authentication-local/src/strategy.ts
=> fix: LocalStrategy authenticates without username

packages/express/index.d.ts
If provided a logger should have `info` property, which is used [here](https://github.com/feathersjs/feathers/blob/eae036b16f0bb3597cd96945ca1b8b4c78b8819c/packages/express/lib/error-handler.js#L34).
Instead of `void | null`, just `void` for return type of logging functions.
`msg` is not a `string`, but `any` since it is used to log errors (as shown in link above) and they might not be a string.
`error` property is required now, if you don't want to log stuff, just do not provide `logger` since it is optional already.
=> fix: Add info to express error handler logger type

packages/authentication-client/package.json, packages/authentication-local/package.json, packages/authentication-oauth/package.json, packages/authentication-oauth/src/index.ts, packages/authentication/package.json, packages/authentication/src/service.ts, packages/configuration/package.json, packages/configuration/src/index.ts, packages/feathers/lib/application.js
Minor stuff:
1) Moved `@feathers/*` dependencies from `devDependencies` to `dependencies` if their types are present in a package build.
2) Moved [this line](https://github.com/feathersjs/feathers/blob/13b3dbdf8133bce2833a56bfbd0f0799b0420a8a/packages/authentication/src/service.ts#L100) up, since no need to call `getPayload` and `getTokenOptions` if their result is irrelevant.
3) [Here](https://github.com/feathersjs/feathers/blob/13b3dbdf8133bce2833a56bfbd0f0799b0420a8a/packages/feathers/lib/application.js#L73) used `location` as is, without prepending slash, as it will be stripped anyway.
4) In [`@feathersjs/configuration`](https://github.com/feathersjs/feathers/blob/13b3dbdf8133bce2833a56bfbd0f0799b0420a8a/packages/configuration/src/index.ts) allow calling without an argument and use …
=> fix: minor stuff

packages/authentication-oauth/package.json
Getting this error when updating packages via npm.
Warning "@feathersjs/authentication-oauth > grant-profile@0.0.5" has incorrect peer dependency "grant@>=4.6.3".
Seems grant-profile is set to depend on grant 4.6.3 or higher where as we are using 4.6.2
Pretty straight forward update.
Might be some other changes to take note of [here](https://github.com/simov/grant/blob/master/CHANGELOG.md#v463-20190907).
=> Nudge grant version up

packages/authentication-client/src/core.ts, packages/primus/index.d.ts, packages/socketio/index.d.ts
- `authentication-client`: `params` as a second optional argument for `authenticate`. Useful when you implement custom auth strategies.
- `primus`: does not have `SOCKET_KEY` anymore and the options argument is [optional](https://github.com/primus/primus/blob/c3d1d13963695002d6ced1ff2b7d8fda9d1ead5b/index.js#L32).
- `socketio` and `primus`: return configure functions that take an app as an argument.
This commit have description. If you prefer to have multiple one-line pull requests instead of such combo ones, let me know.
=> fix: Typing updates

packages/feathers/lib/version.js, packages/feathers/package.json
This pull request makes sure that Lerna detects dependency updates properly by resetting the `app.version` in `@feathersjs/feathers` after publishing. Otherwise every version update will also cause a version bump in every package that depends on `@feathersjs/feathers` (which is pretty much all of them) and that's not really how semantic versioning should work.
=> fix: Reset version number after every publish

packages/authentication-client/src/core.ts, packages/authentication-client/src/index.ts, packages/authentication/src/core.ts, packages/authentication/src/hooks/authenticate.ts, packages/authentication/src/jwt.ts, packages/authentication/src/service.ts, packages/authentication/test/jwt.test.ts
Small types and consistency style fixes. But also one real fix:
`handleConnection` method of `AuthenticationBase` and `JWTStrategy` was never called in response to `disconnect` event, so when a jwt expiration timer emitted `disconnect` `connection.authentication` was not removed and the timer was not cleared. Added listener for `disconnect` event to fix this. Also added `expirationTimers.delete` after a timer is cleared and `lt.clearTimeout` before a timer is set (to ensure that only one timer per connection exist at a time, otherwise multiple calls to `reAuthenticate` with force can create more than one timer).
=> fix: Small improvements

packages/commons/src/hooks.ts
We should be able to modify or delete this value.
In a particular case it will avoid me this kind of error:
```
Uncaught TypeError: Cannot redefine property: __hooks
```
```
Uncaught TypeError: Cannot delete property '__hooks' of #<Object>
```
=> __hooks become writable and configurable

packages/authentication-client/src/index.ts
In some cases browsers (like Brave when all cookies are blocked) throw an error when accessing `window.localStorage`. This pull request improves the initialization to return a fallback memory storage on any localStorage initialization error.
Closes #1344
=> fix: Improve authentication client default storage initialization

packages/adapter-commons/src/service.ts
Changes back some things from #1567 since it broke type compatibility in existing applications (like the feathers-chat and generated application).
=> fix: Remove adapter commons type alternatives

packages/authentication-oauth/src/express.ts, packages/authentication-oauth/src/utils.ts
Apparently `express-session` always throws a warning in production when it is initialized even if the middleware is not used. This PR makes initialization on-demand.
Closes #1646
=> fix: Only initialize default Express session if oAuth is actually used

packages/authentication/src/core.ts, packages/authentication/src/index.ts, packages/authentication/src/jwt.ts, packages/authentication/src/service.ts, packages/errors/index.d.ts, packages/express/index.d.ts, packages/feathers/index.d.ts
- `getStrategies` in `AuthenticationBase` does not return `undefined` values.
- export `ConnectionEvent` in `@feathersjs/authentication`.
- `Date.now()` instead of `new Date().getTime()`.
- Add `authenticated` to `Params` definition.
- Do not use `_.get` where simply getting property works.
- Type numbered errors in `@feathersjs/errors`.
- Continuing #1609, extend express application type with feathers application.
- Reverting one change in #1605, add `AuthenticationService extends ServiceAddons<AuthenticationResult>` to use `.hooks` and `.publish` on a service instance.
- Type `methods` in a service.
- Type `httpMethod` for express rest.
=> fix: Small type improvements

packages/authentication/package.json
This fixes the following error that occurs when compiling a TypeScript project that uses `@feathersjs/authentication`.
> node_modules/@feathersjs/authentication/lib/core.d.ts:2:52 - error TS7016: Could not find a declaration file for module 'jsonwebtoken'. 'node_modules/jsonwebtoken/index.js' implicitly has an 'any' type.
>   Try `npm install @types/jsonwebtoken` if it exists or add a new declaration (.d.ts) file containing `declare module 'jsonwebtoken';`
> 
> 2 import { SignOptions, Secret, VerifyOptions } from 'jsonwebtoken';
Since `@feathersjs/authentication` includes exports from `jsonwebtoken` in `core.d.ts`, it should include `@types/jsonwebtoken` in its `dependencies` rather than its `devDependencies`. Otherwise, users must install `@types/jsonwebtoken` manually, which is a poor …
=> fix: Add jsonwebtoken TypeScript type dependency

packages/authentication/src/hooks/authenticate.ts, packages/authentication/src/jwt.ts, packages/authentication/test/hooks/authenticate.test.ts
Lodash `_.merge` makes a copy of objects including the `connection` which breaks the reference to the required object. To fix this problem, we still create a copy of `params` (so the original version does not get modified) but use the shallow `Object.assign`.
Closes #1629
Closes #1641 
Closes #1671
=> fix(authentication): Retain object references in authenticate hook

packages/authentication-client/src/core.ts
This PR updates the authentication client to defer authentication as soon as a socket disconnects instead of only on socket reconnect because calls made while disconnected will still get a `NotAuthenticated` errors.
=> fix(authentication-client): Reset authentication promise on socket disconnect

packages/feathers/lib/hooks/base.js, packages/feathers/test/hooks/hooks.test.js, packages/rest-client/test/index.test.js
Otherwise it's pretty difficult to figure out where it happened. Still not ideal but will be improved further with the new hook system.
=> fix(core): Improve hook missing parameter message by adding the service name

packages/authentication-local/test/fixture.js, packages/express/lib/authentication.js, packages/express/test/authentication.test.js, packages/socketio/lib/middleware.js
To allow separate strategies for creating JWTs and parsing headers. Not every strategy should be allowed to create JWTs (e.g. API keys) and is only used for parsing HTTP requests. This adds a separate configuration value that allows that. The flow will also be clarified in the docs.
=> feat(authentication): Add parseStrategies

lerna.json, package.json, packages/adapter-commons/package.json, packages/adapter-tests/package.json, packages/authentication-client/package.json, packages/authentication-local/package.json, packages/authentication-oauth/package.json, packages/authentication/package.json, packages/client/package.json, packages/commons/package.json, packages/configuration/package.json, packages/errors/package.json, packages/express/package.json, packages/feathers/package.json, packages/primus/package.json, packages/rest-client/package.json, packages/socketio-client/package.json, packages/socketio/package.json, packages/tests/package.json, packages/transport-commons/package.json
Made a mistake in setting `engines` to 12 but it should be 10 which is the current LTS.
=> chore: Fix Node engines version to current LTS (10)

packages/authentication-local/test/strategy.test.ts
password was written with 3 s (passsword) which resulted in a test that would always pass regardless of whether the password was removed from the response or not.
=> fix: typo in password

packages/feathers/index.d.ts
Made the `HookMap` and `HooksObject` interfaces generic. Beyond adding options for one to specify types for the associated `HookContext`, this helps a lot with the reusability of these interfaces.
=> Make TypeScript HookMap and HooksObject interfaces generic.

.github/workflows/nodejs.yml, packages/express/index.d.ts
Support typings for [custom service middleware](https://docs.feathersjs.com/api/express.html#custom-service-middleware). Also typings issue mentioned in https://github.com/feathersjs/feathers/issues/1744#issuecomment-568262906
=> fix: Updated typings for express middleware

packages/authentication-oauth/src/express.ts, packages/authentication-oauth/test/express.test.ts, packages/authentication-oauth/test/fixture.ts
This pull request allows to use `req.feathers` in oAuth strategies as mentioned in https://github.com/feathersjs/feathers/pull/1869#issuecomment-601221026.
- Closes https://github.com/feathersjs/docs/pull/1447
- Closes https://github.com/feathersjs/feathers/pull/1869
=> fix(authentication-oauth): Allow req.feathers to be used in oAuth authentication requests

packages/errors/lib/index.js, packages/errors/test/index.test.js
This adds the 410/Gone message to feathersjs/errors. This one's been in the various RFCs for a long time,  not sure why it's missing.
=> Add 410 Gone to errors

packages/adapter-commons/src/service.ts
Just a simple tweak that defines the missing types for the [`pagination`](packages/adapter-commons/src/service.ts#L23) options of [`ServiceOptions`](packages/adapter-commons/src/service.ts#L19). Here I'm assuming that the only supported options are `max` and `default`. 
I was unable to find anything that would indicate that there are additional options. But I assume the available options could be tied to the database adapter in use? If the pagination object should accept any list of customizable options, perhaps we could consider refactoring to something like the following snippet;
```ts
export interface ServiceOptions {
events: string[];
multi: boolean|string[];
id: string;
paginate: {
[key: string]: any;
default?: number;
max?: number;
}
whitelist: string[];
filters: string[];
}
``` …
=> Add type keys to service pagination options.

packages/authentication/src/jwt.ts, packages/authentication/test/jwt.test.ts
This pull request makes sure that all connection information gets removed on logout.
Closes #1883
=> fix(authentication): Remove entity from connection information on logout

packages/feathers/index.d.ts
A simple tweak to the HookContext's `method` property type declaration. This specifies a union type with the possible string types for the `method` property. Essentially allowing for autocompletes by the IDEs that support TypeScript, as well as warnings should you mistype a method name.
=> Use stricter type for HookContext 'method' prop

packages/express/lib/index.js
There is a small typo in packages/express/lib/index.js.
Should read `service` rather than `serivce`.
=> docs: Fix simple typo, serivce -> service

packages/adapter-commons/src/service.ts
Similar to #1567, improve typings for `create`, `patch`, `remove` overloads for DB Common API.
=> fix: Improve Service typings for DB Common API

packages/feathers/index.d.ts
Yet another TypeScript type definition tweak here 😊
This pull request adds the hook-less service methods described in [the Feathers migration documentation](https://docs.feathersjs.com/guides/migrating.html#hook-less-service-methods) to the `Service` type, allowing for usage of these methods with proper type hinting.
Additionally; I've gone ahead and added inline documentation to all service methods in the form of JSDocs, allowing for nice quick-reference documentation for those running modern code editors and IDEs.
[![image](https://user-images.githubusercontent.com/4034561/80670389-619fe480-8aaf-11ea-947e-434d6f930703.png)](https://globglo.gabgalab.io/x45h9Y3DWUci)
=> chore(docs): Add inline docs to service methods

packages/authentication-oauth/src/strategy.ts, packages/feathers/index.d.ts
I thought this might be a better way to have a conversation about #1970.
The goal is to let typescript automatically infer the return type for `find` methods based on `params.paginate`.
I do not think it is dependent on any other PRs.
Adding these type definitions did have one unexpected side effect where TS no longer approved of line 106 in `packages/authentication-oauth/src/strategy.ts`, but it was such a little change that I included it in this PR.
I can think of two things that I would really like some feeback on:
1.  The main `ServiceMethods<T>` definition for `find` has the signature `find (params?: Params): Promise<T | T[] | Paginated<T>>;`, and the `Promise<T>` result is not included in the overloads
2. I am not sure if changes similar to the one in the `strategy.ts` file would be …
=> feat: add overload types for `find` service methods

packages/authentication/src/hooks/authenticate.ts
=> fix(authentication): Include query params when authenticating via authenticate hook

packages/authentication/src/jwt.ts, packages/authentication/test/jwt.test.ts
=> fix(authentication): Omit query in JWT strategy

packages/authentication-oauth/src/strategy.ts, packages/feathers/index.d.ts
This pull request reverts #1972 which breaks some assumption for other adapters. It will be added in the adapter common types via https://github.com/feathersjs/databases/pull/9 instead.
=> "fix(typescript): Revert add overload types for `find` service methods (#1972)

packages/authentication-local/src/strategy.ts, packages/authentication/src/jwt.ts, packages/authentication/test/jwt.test.ts
Brings both local-strategy and jwt-strategy into alignment.
Added getEntityQuery to JWT strategy, allows extending JWT class to include additional query parameters in entity lookup.
Closes https://github.com/feathersjs/feathers/issues/2007
=> Add JWT getEntityQuery

CHANGELOG.md
I really enjoyed using this project, nice work! Caught a couple of typos in the CHANGELOG.md though 😛
=> chore: Update CHANGELOG.md, fix typo(s)
