lib/application.js, lib/providers/rest/index.js, lib/providers/rest/wrappers.js, lib/providers/socket/commons.js, lib/providers/socket/primus.js, lib/providers/socket/socketio.js, package.json
This pull request adds the [debug](https://www.npmjs.com/package/debug) module and debug messages to track what the application is doing. Closes #114.
=> Adding debug module and messages.

contributing.md, docs/api.md, docs/faq.md, docs/guide.md
Currently all documentation was contained in the `gh-pages` branch. Moving it back into the main repository since it is a better place (website deployment needs to be streamlined then tough).
=> Moving documentation into the main repository.

lib/mixins/event.js, test/providers/primus.test.js, test/providers/service-fixture.js, test/providers/socketio.test.js
This pull request allows services to dispatch custom events through sockets. Closes #111.
=> Allow services to dispatch custom events.

lib/application.js, lib/providers/rest/index.js, test/application.test.js
=> Handle middleware passed after the service to app.use

lib/mixins/event.js, lib/providers/rest/index.js, lib/providers/rest/wrappers.js, test/mixins/event.test.js, test/providers/primus.test.js, test/providers/rest.test.js, test/providers/service-fixture.js, test/providers/socketio.test.js
Closes #144. With pair-help from the awesome @marshallswain.
=> Add ability to create, update, patch and remove many

package.json, src/client/index.js, src/feathers.js, src/index.js, test/application.test.js, test/distributed.test.js
Which also makes the client work with non-Browser and Node loaders like React Native.
/cc @corymsmith
=> Reorganizing packages to not load Express

index.html
Hi,
There is no link on first button. I added it.
=> Fix link to docs

src/application.js, test/application.test.js
=> Test and fix for allowing services with only a setup method

test/application.test.js
See https://nodesecurity.io/advisories/99
=> Set rejectUnauthorized explicitly

src/mixins/event.js, test/mixins/event.test.js
Create an app reference on scope of default function and referenced below inside of hook key app.
=> Create an app reference on hook object

.istanbul.yml, readme.md
The NPM badges made it pretty noisy.
=> Remove NPM badges and fix code climate badge

test/application.test.js, test/client.test.js
Since we started it already, this should increase code coverage to almost 100%.
=> Increase code coverage

package.json, src/application.js, src/client/express.js, src/client/index.js, src/feathers.js, src/index.js, src/mixins/event.js, src/mixins/index.js, src/mixins/normalizer.js, src/mixins/promise.js, test/application.test.js, test/client.test.js, test/distributed.test.js, test/mixins/event.test.js, test/mixins/normalizer.test.js, test/mixins/promise.test.js
This installd and implements semistandard for linting.  Uses eslint-if-supported for tests.
=> jshint —> semistandard

package.json
Closes https://github.com/feathersjs/feathers-authentication-client/issues/11
=> Update feathers-commons to use latest

index.d.ts
=> No Pagination in Typescript #520

package.json, src/index.js
=> Remove explicit loading of babel-polyfill

index.d.ts
I am not sure if it is only my problem, but i got an compilation erorr without types defined.
=> Return types needed

readme.md
Made the url woody (point to chat)
=> Examples url is tinny (broken)

index.d.ts
needs https://github.com/feathersjs/feathers-reactive/pull/69 and https://github.com/feathersjs/feathers-hooks/pull/168
=> [typings] Make generic type of Service default to any

package-lock.json, package.json
`debug` and `express` needed to be updated.
=> Update to latest secure dependencies

package.json
=> Move Typescript declaration dependency into devDependencies

changelog.md, package-lock.json, package.json
This pull request adds a Changelog using the same changelog generator we are using for other repositories but only including pull requests.
Closes #686, closes #665
=> Add changelog back

lib/application.js, test/application.test.js
=> Also pass app object as parameter to configure callbacks

readme.md
According with https://github.com/feathersjs/express, and because I find it more appropriate, what do you think?
=> Rename expressify to express

lib/index.js, test/application.test.js
For https://github.com/feathersjs/feathers/issues/733
=> Add default export for better ES module (TypeScript) compatibility

lib/events.js, package-lock.json, test/events.test.js
Fixed emit to use Array.isArray and emit multiples for array results.
Updated tests with array values to ensure the emits were handled properly.
Refactored the tests to bring the value below the testing limit of 5
=> Updated to handle array emit for service results.

readme.md
The supported versions section has been moved to [the FAQ](https://docs.feathersjs.com/faq/readme.html).
=> Update Readme to correspond with latest release

lib/index.js, package-lock.json, package.json, test/application.test.js
Exports SKIP from `(@feathersjs/commons).hooks.SKIP`.
=> Add ability to skip all following hooks

readme.md
We have a Russian community. I added a link to Readme.
=> Add Russian Telegram community

lib/hooks.js, test/hooks/hooks.test.js
Follow up on https://github.com/feathersjs/feathers/pull/818
Closes https://github.com/feathersjs/express/issues/21
=> Handle errors in error hooks properly

package-lock.json, test/application.test.js
Here is a test that corresponds to the problem described in #863.
=> Add 'services conserve Symbols' test

package-lock.json, package.json
=> Update to latest Uberproto and other dependencies

.gitignore, lerna.json, package-lock.json, packages/authentication-client/package-lock.json, packages/authentication-jwt/package-lock.json, packages/authentication-local/package-lock.json, packages/authentication-oauth1/package-lock.json, packages/authentication-oauth2/package-lock.json, packages/authentication/package-lock.json, packages/cli/package-lock.json, packages/errors/package-lock.json, packages/express/package-lock.json, packages/feathers/package-lock.json, packages/generator-feathers-plugin/package-lock.json, packages/generator-feathers/package-lock.json, packages/rest-client/package-lock.json, packages/socketio-client/package-lock.json, packages/transport-commons/package-lock.json
=> Ignore changes and add package-lock.json

packages/generator-feathers/generators/connection/templates/mongodb.js, packages/generator-feathers/generators/connection/templates/rethinkdb.js
This PR catches database connection initialization errors.
Fixes https://github.com/feathersjs/feathers/issues/1037
=> Catch connection initialization errors

package-lock.json, package.json, packages/authentication-client/package.json, packages/authentication-jwt/package.json, packages/authentication-local/package.json, packages/authentication-oauth1/package.json, packages/authentication-oauth2/package.json, packages/authentication/package.json, packages/cli/package.json, packages/client/package.json, packages/commons/package.json, packages/configuration/package.json, packages/errors/package.json, packages/express/package.json, packages/feathers/package.json, packages/generator-feathers-plugin/package.json, packages/generator-feathers/package.json, packages/primus-client/package.json, packages/primus/package.json, packages/rest-client/package.json, packages/socketio-client/package.json, packages/socketio/package.json, packages/transport-commons/package.json
This should make things work on Windows as well. Related to https://github.com/feathersjs/feathers/issues/1049
=> Use linked instead of top level Mocha

packages/authentication-client/package.json, packages/authentication-jwt/package.json, packages/authentication-local/package.json, packages/authentication-oauth1/package.json, packages/authentication-oauth2/package.json, packages/authentication/package.json, packages/cli/package.json, packages/client/package.json, packages/commons/package.json, packages/configuration/package.json, packages/errors/package.json, packages/express/package.json, packages/feathers/package.json, packages/generator-feathers-plugin/package.json, packages/generator-feathers/package.json, packages/primus-client/package.json, packages/primus/package.json, packages/rest-client/package.json, packages/socketio-client/package.json, packages/socketio/package.json, packages/transport-commons/package.json
Addresses https://github.com/feathersjs/feathers/commit/7ecc6a7c0e52b16f944092a6626d0e420e24e0be#commitcomment-30869982, follow up on #1051.
=> Make Mocha a proper devDependency

.codeclimate.yml, .nycrc, package-lock.json, package.json, packages/authentication-jwt/lib/verifier.js, packages/authentication-jwt/test/index.test.js, packages/client/test/fixture.js, packages/express/test/rest/index.test.js
Also fixes the excludes for code coverage.
=> Properly configure and run code linter

packages/express/test/rest/index.test.js
Which might mean that it closes #1096
=> Verify that the error handler works on nested routes (#1096)

packages/authentication-local/lib/strategy.js, packages/authentication-local/test/fixture.js, packages/authentication-local/test/strategy.test.js, packages/authentication/lib/core.js, packages/authentication/lib/jwt.js, packages/authentication/lib/options.js, packages/authentication/test/jwt.test.js
Adds the ability to verify the configuration of authentication strategies
=> feat: Add strategy verifyConfiguration and improve JWT option handling

packages/authentication-client/test/integration/fixture.ts, packages/authentication-local/test/fixture.js, packages/authentication-oauth/test/fixture.ts, packages/authentication/src/options.ts, packages/express/lib/authentication.js, packages/express/test/authentication.test.js
Does not need to be two different options.
=> fix: Merge httpStrategies and authStrategies option

packages/feathers/index.d.ts
(If you have not already please refer to the contributing guideline as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#pull-requests))
If so, please mention them to keep the conversations linked together.
If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.
Your PR will be reviewed by a core team member and they will work with you to get your changes merged in a timely manner. If merged your PR will automatically be added to the changelog in the next release.
If your changes involve documentation updates please mention that and link the appropriate PR in [feathers-docs](https://github.com/feathersjs/feathers-docs).
Thanks for contributing …
=> finally should be optional

packages/authentication/src/hooks/authenticate.ts, packages/authentication/test/fixtures.ts, packages/authentication/test/jwt.test.ts
Fixes https://github.com/feathersjs/feathers/issues/1360
=> fix: Set authenticated: true after successful authentication

packages/transport-commons/src/channels/index.ts, packages/transport-commons/src/channels/mixins.ts
Normalise types of `PublishMixin`, `ServiceAddons` and `Application` for `publish`/`registerPublish`:
- an event is `string` or `ALL_EVENTS` symbol.
- `callback` is now `publisher` in argument and variable naming.
- a publisher returns a channel, an array of channels, void or a promise* for those.
- return value is `this`.
\* - before a promise was not present in types and not mentioned in documentation, but based on [this line](https://github.com/feathersjs/feathers/blob/28888a1a6bd61eac778573234e2d668488f9989e/packages/transport-commons/src/channels/index.ts#L81) it is possible currently to return a promise. We can remove this feature from types and remove `Promise.resolve` from that line if this should not be supported.
Plus small performance improving in publishing: no point in …
=> fix: Improve transport-commons types

package-lock.json, package.json, packages/adapter-commons/package.json, packages/authentication-client/package.json, packages/authentication-local/package.json, packages/authentication-oauth/package.json, packages/authentication/package.json, packages/client/package.json, packages/commons/package.json, packages/configuration/package.json, packages/express/package.json, packages/primus-client/package.json, packages/primus/package.json, packages/rest-client/package.json, packages/socketio/package.json, packages/tests/package.json, packages/transport-commons/package.json
This will also include the latest Lodash security fix.
Closes https://github.com/feathersjs/feathers/pull/1437
Closes https://github.com/feathersjs/feathers/issues/1447
=> chore: Update all dependencies and add types mapping to package.json

.travis.yml
=> chore: Update Travis Node versions

packages/authentication-client/src/core.ts, packages/authentication-client/test/index.test.ts
Closes https://github.com/feathersjs/feathers/issues/1449
=> fix: Do not error in authentication client on logout

.travis.yml
=> chore: Force install libgconf which stopped working in Travis

package-lock.json, packages/authentication/src/jwt.ts, packages/transport-commons/src/socket/index.ts
=> fix: Add getEntityId to JWT strategy and fix legacy Socket authentication

packages/authentication-oauth/package.json
grant-profile now supports custom `profile_url` parameter #1452
=> chore: Update grant-profile

packages/transport-commons/src/socket/index.ts, packages/transport-commons/src/socket/utils.ts, packages/transport-commons/test/socket/utils.test.ts
=> fix: Fix regression in transport commons

package-lock.json, packages/authentication/package.json, packages/authentication/src/jwt.ts
=> fix: Use long-timeout for JWT expiration timers

packages/authentication/src/jwt.ts
This PR adds a check for if the access token is undefined. 
Fixes #1568.
Nope, AFAIK.
This fix does not yet have a test.
=> fix: check for undefined access token

package-lock.json, packages/client/package.json, packages/client/webpack.config.js, packages/feathers/lib/hooks/base.js, packages/feathers/lib/hooks/index.js, packages/feathers/package.json, packages/feathers/test/application.test.js, packages/feathers/test/hooks/app.test.js, packages/feathers/test/hooks/async.test.js, packages/hooks/lib/compose.js, packages/hooks/lib/index.js, packages/rest-client/test/index.test.js
https://github.com/feathersjs/feathers/issues/932
=> enable async hooks

packages/authentication/src/core.ts, packages/authentication/test/core.test.ts
Since the cause of the error wasn't very clear before.
=> fix: Improve error message when authentication strategy is not allowed

packages/primus-client/lib/index.js, packages/rest-client/lib/index.js, packages/socketio-client/lib/index.js
=> fix: Change this reference in client libraries to explicitly passed app

packages/adapter-commons/src/filter-query.ts, packages/adapter-commons/test/filter-query.test.ts
=> fix: Check query  for NaN

packages/authentication-oauth/src/strategy.ts, packages/authentication-oauth/test/strategy.test.ts
=> fix(authentication-oauth): Allow hash based redirects

package.json, packages/adapter-commons/package.json, packages/adapter-tests/package.json, packages/authentication-client/package.json, packages/authentication-local/package.json, packages/authentication-oauth/package.json, packages/authentication/package.json, packages/client/package.json, packages/commons/package.json, packages/configuration/package.json, packages/express/package.json, packages/feathers/package.json, packages/primus-client/package.json, packages/primus/package.json, packages/rest-client/package.json, packages/socketio-client/package.json, packages/socketio/package.json, packages/tests/package.json, packages/transport-commons/package.json
Pointing to [our Opencollective](https://opencollective.com/feathers).
=> chore(package): Add npm funding field

packages/transport-commons/src/client.ts, packages/transport-commons/test/client.test.ts
Closes https://github.com/feathersjs/feathers/issues/1704
=> fix(transport-commons): Allow to properly chain SocketIo client.off

packages/authentication-oauth/src/express.ts, packages/authentication-oauth/src/strategy.ts, packages/authentication-oauth/test/strategy.test.ts
Referred to this bug https://github.com/feathersjs/feathers/issues/1591 
Fixed set oauth redirect URL dynamically.
=> feat(authentication-oauth): Set oAuth redirect URL dynamically

packages/transport-commons/src/channels/index.ts, packages/transport-commons/test/channels/dispatch.test.ts
=> fix: Gracefully handle errors in publishers

package-lock.json, packages/adapter-commons/src/filter-query.ts, packages/adapter-commons/test/filter-query.test.ts
=> fix(adapter-commons): Filter arrays in queries

packages/authentication/src/service.ts, packages/feathers/index.d.ts
`connection` is in `Params` and defined in `transport-commons`.
=> fix: Add `params.authentication` type, remove `hook.connection` type

packages/feathers/readme.md, readme.md
This uses the updated verbiage as the home page:
https://github.com/feathersjs/website/pull/14
=> chore(docs): update intro readme text to be in line with homepage

.github/workflows/nodejs.yml
=> Add LTS node version to test

packages/authentication/src/jwt.ts, packages/authentication/test/jwt.test.ts
For https://github.com/feathersjs/feathers/issues/1554
=> fix(authentication): Improve JWT strategy configuration error message

package-lock.json, packages/authentication-local/src/hooks/hash-password.ts, packages/authentication-local/src/hooks/protect.ts, packages/authentication-local/src/strategy.ts, packages/authentication-local/test/strategy.test.ts, packages/authentication-oauth/src/index.ts, packages/authentication/src/core.ts, packages/authentication/src/hooks/authenticate.ts, packages/authentication/src/hooks/connection.ts, packages/authentication/src/jwt.ts, packages/authentication/src/service.ts, packages/authentication/test/jwt.test.ts, packages/authentication/test/service.test.ts, packages/express/lib/authentication.js, packages/primus/test/index.test.js, packages/socketio/test/index.test.js, packages/transport-commons/src/channels/index.ts, packages/transport-commons/src/socket/utils.ts
=> use lodash modularized

packages/authentication-oauth/src/strategy.ts
And remove provider field for other calls
- Closes https://github.com/feathersjs/feathers/issues/1930
- Closes https://github.com/feathersjs/feathers/issues/1926
- Related to https://github.com/feathersjs/feathers/pull/1886
=> fix(authentication-oauth): Add getEntity method to oAuth

packages/authentication-local/src/hooks/hash-password.ts, packages/authentication-local/test/fixture.js, packages/authentication-local/test/hooks/hash-password.test.ts
Closes https://github.com/feathersjs/feathers/issues/1931
=> fix(authentication-local): Allow to hash passwords in array data

package-lock.json, package.json, packages/authentication-client/package.json, packages/authentication-client/test/index.test.ts, packages/authentication-client/test/integration/express.test.ts, packages/authentication-local/package.json, packages/authentication-oauth/package.json, packages/authentication-oauth/test/fixture.ts, packages/authentication/package.json, packages/authentication/src/core.ts, packages/client/package.json, packages/commons/package.json, packages/configuration/package.json, packages/errors/package.json, packages/express/package.json, packages/feathers/package.json, packages/primus-client/package.json, packages/primus/package.json, packages/rest-client/package.json, packages/socketio-client/package.json, packages/socketio/package.json, packages/tests/package.json, packages/transport-commons/package.json
Also fixes some TypeScript upgrade pain.
Closes #1922
=> chore(dependencies): Update all non-breaking dependencies and fix TypeScript usage

packages/feathers/index.d.ts
Hi, this is my very first PR and contribution to OSS. Hope I did it right.
This pull request adds `event` prop to `HookContext` interface
=> chore(hooks): add event property to HookContext

package-lock.json, package.json, packages/authentication-client/package.json, packages/authentication-local/package.json, packages/authentication-oauth/package.json, packages/authentication/package.json, packages/client/package.json, packages/commons/package.json, packages/configuration/package.json, packages/feathers/package.json, packages/rest-client/package.json, packages/socketio/package.json, packages/tests/package.json, packages/transport-commons/package.json
Closes https://github.com/feathersjs/feathers/pull/2012
=> chore(dependencies): Update all dependencies
